In [68]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter
metadata = dict(title = "Pipe Animation",artist = "Matplotlib")
writer = FFMpegWriter(fps=15,metadata=metadata, bitrate=200000)

In [69]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A):
    maxX = A.shape[0]
    maxY = A.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [70]:
nParticles = 20000
maxX = 200
maxY = 40

In [71]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A[:,0] = 1
A[:,maxY-1] = 1
print(A.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [72]:
succesful_particles = 0
total_steps = 0
max_steps_per_particle = maxX*maxY*2
frames = []
for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x = maxX - 1
    y = maxY//2; #always start at upper limit
    current_steps = 0
    attached = False

    while not attached and current_steps < max_steps_per_particle:
        current_steps += 1
        x_org,y_org = x,y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.1):
            x += 1
        elif(r < 0.6):
            x -= 1
        elif(r < 0.8):
            y += 1
        else:
            y -= 1
        #boundaries
        if x >= maxX:
            x = x_org
            continue
        if x<0:
            succesful_particles += 1
            total_steps += current_steps
            break
        
        if y<0 or y>= 39: 
            total_steps += current_steps
            break
        if A[x,y] == 1:
            total_steps += current_steps
            break
display(A)
probability = succesful_particles/nParticles
print("The number of particles that made it to the end is", succesful_particles)
print("The probability that a particle reaches the end of the pip is", probability*100, "percent")

The number of particles that made it to the end is 12385
The probability that a particle reaches the end of the pip is 61.925 percent


In [75]:
nFrames = 50
B=np.zeros((nFrames,maxX,maxY))

def display(A,B):
    maxX = A.shape[0]
    maxY = A.shape[1]

    m2 = np.max(B)
    B[A[:,:] == 1] = m2
    if (m2 > 0):
        m1 = np.min(B[B[:,:]>0])
        if (m1==m2): m1=m2/2
        B[B[:,:]==0] = m1*(m1/m2)**(1/10)

    D = np.zeros((maxY, maxX))
    for iy in range(0,maxY):
        D[maxY-1-iy,:] = np.log(B[:,iy])
    
    plt.imshow(D);
    plt.axis('off');
    plt.show()
    plt.draw()
    plt.pause(0.1)

In [84]:
succesful_particles = 0
total_steps = 0
max_steps_per_particle = maxX*maxY*2
nFrames=50
record_step = 10
frame_index = 0

for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x = maxX - 1
    y = maxY//2; #always start at upper limit
    current_steps = 0
    attached = False

    while not attached and current_steps < max_steps_per_particle:
        current_steps += 1
        x_org,y_org = x,y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.1):
            x += 1
        elif(r < 0.6):
            x -= 1
        elif(r < 0.8):
            y += 1
        else:
            y -= 1
        #boundaries
        if x >= maxX:
            x = x_org
            continue
        if x<0:
            succesful_particles += 1
            total_steps += current_steps
            break
        
        if y<=1 or y>= 38: 
            total_steps += current_steps
            break
        if A[x,y] == 1:
            total_steps += current_steps
            break

        if current_steps % record_step == 0 and frame_index < nFrames:
            B[frame_index,x,y] += 1
            frame_index +=1
probability = succesful_particles/nParticles
print("The number of particles that made it to the end is", succesful_particles)
print("The probability that a particle reaches the end of the pip is", probability*100, "percent")

for f in range(nFrames):
    display(A,B[f,:,:])

The number of particles that made it to the end is 12515
The probability that a particle reaches the end of the pip is 62.575 percent


In [105]:
#Rhombus in the center

In [106]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A2):
    maxX = A2.shape[0]
    maxY = A2.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A2[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [107]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A2 = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A2[:,0] = 1
A2[:,maxY-1] = 1
print(A2.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [108]:
nFrames = 50
B=np.zeros((nFrames,maxX,maxY))

def display(A2,B):
    maxX = A2.shape[0]
    maxY = A2.shape[1]

    m2 = np.max(B)
    B[A2[:,:] == 1] = m2
    if (m2 > 0):
        m1 = np.min(B[B[:,:]>0])
        if (m1==m2): m1=m2/2
        B[B[:,:]==0] = m1*(m1/m2)**(1/10)

    D = np.zeros((maxY, maxX))
    for iy in range(0,maxY):
        D[maxY-1-iy,:] = np.log(B[:,iy])
    
    plt.imshow(D);
    plt.axis('off');
    plt.show()
    plt.draw()
    plt.pause(0.1)

In [109]:
xc, yc = maxX//2, maxY//2
rx = 20
ry = 10
for ix in range(maxX):
    for iy in range(maxY):
        distance_ratio = abs(ix - xc)/rx + abs(iy - yc)/ry
        if distance_ratio <= 1:
            A2[ix,iy] = 1

In [110]:
succesful_particles = 0
total_steps = 0
max_steps_per_particle = maxX*maxY*2
nFrames=50
record_step = 10
frame_index = 0

for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x = maxX - 1
    y = maxY//2; #always start at upper limit
    current_steps = 0
    attached = False

    while not attached and current_steps < max_steps_per_particle:
        current_steps += 1
        x_org,y_org = x,y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.1):
            x += 1
        elif(r < 0.6):
            x -= 1
        elif(r < 0.8):
            y += 1
        else:
            y -= 1
        #boundaries
        if x >= maxX:
            x = x_org
            continue
        if x<0:
            succesful_particles += 1
            total_steps += current_steps
            break
        
        if y<=1 or y>= 38: 
            total_steps += current_steps
            break
        if A2[x,y] == 1:
            total_steps += current_steps
            break

        if current_steps % record_step == 0 and frame_index < nFrames:
            B[frame_index,x,y] += 1
            frame_index +=1
probability = succesful_particles/nParticles
print("The number of particles that made it to the end is", succesful_particles)
print("The probability that a particle reaches the end of the pip is", probability*100, "percent")

for f in range(nFrames):
    display(A2,B[f,:,:])

The number of particles that made it to the end is 775
The probability that a particle reaches the end of the pip is 3.875 percent


In [111]:
#the particles that make it through decrease drastically!!! To around 4%, instead of 62%

In [112]:
#half tall rhombus

In [128]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A3):
    maxX = A3.shape[0]
    maxY = A3.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A3[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [129]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A3 = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A3[:,0] = 1
A3[:,maxY-1] = 1
print(A3.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [130]:
nFrames = 50
B=np.zeros((nFrames,maxX,maxY))

def display(A3,B):
    maxX = A3.shape[0]
    maxY = A3.shape[1]

    m2 = np.max(B)
    B[A3[:,:] == 1] = m2
    if (m2 > 0):
        m1 = np.min(B[B[:,:]>0])
        if (m1==m2): m1=m2/2
        B[B[:,:]==0] = m1*(m1/m2)**(1/10)

    D = np.zeros((maxY, maxX))
    for iy in range(0,maxY):
        D[maxY-1-iy,:] = np.log(B[:,iy])
    
    plt.imshow(D);
    plt.axis('off');
    plt.show()
    plt.draw()
    plt.pause(0.1)

In [131]:
xc, yc = maxX//2, maxY//2
rx = 20
ry2 = 5
for ix in range(maxX):
    for iy in range(maxY):
        distance_ratio = abs(ix - xc)/rx + abs(iy - yc)/ry2
        if distance_ratio <= 1:
            A3[ix,iy] = 1

In [133]:
succesful_particles = 0
total_steps = 0
max_steps_per_particle = maxX*maxY*2
nFrames=50
record_step = 10
frame_index = 0

for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x = maxX - 1
    y = maxY//2; #always start at upper limit
    current_steps = 0
    attached = False

    while not attached and current_steps < max_steps_per_particle:
        current_steps += 1
        x_org,y_org = x,y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.1):
            x += 1
        elif(r < 0.6):
            x -= 1
        elif(r < 0.8):
            y += 1
        else:
            y -= 1
        #boundaries
        if x >= maxX:
            x = x_org
            continue
        if x<0:
            succesful_particles += 1
            total_steps += current_steps
            break
        
        if y<=1 or y>= 38: 
            total_steps += current_steps
            break
        if A3[x,y] == 1:
            total_steps += current_steps
            break

        if current_steps % record_step == 0 and frame_index < nFrames:
            B[frame_index,x,y] += 1
            frame_index +=1
probability = succesful_particles/nParticles
print("The number of particles that made it to the end is", succesful_particles)
print("The probability that a particle reaches the end of the pip is", probability*100, "percent")

for f in range(nFrames):
    display(A3,B[f,:,:])

The number of particles that made it to the end is 3205
The probability that a particle reaches the end of the pip is 16.025 percent


In [134]:
#The percent of particles making it through increases to about 16%!

In [125]:
#Rhombus half as wide

In [135]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A4):
    maxX = A4.shape[0]
    maxY = A4.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A4[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [136]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A4 = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A4[:,0] = 1
A4[:,maxY-1] = 1
print(A4.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [137]:
nFrames = 50
B=np.zeros((nFrames,maxX,maxY))

def display(A4,B):
    maxX = A4.shape[0]
    maxY = A4.shape[1]

    m2 = np.max(B)
    B[A4[:,:] == 1] = m2
    if (m2 > 0):
        m1 = np.min(B[B[:,:]>0])
        if (m1==m2): m1=m2/2
        B[B[:,:]==0] = m1*(m1/m2)**(1/10)

    D = np.zeros((maxY, maxX))
    for iy in range(0,maxY):
        D[maxY-1-iy,:] = np.log(B[:,iy])
    
    plt.imshow(D);
    plt.axis('off');
    plt.show()
    plt.draw()
    plt.pause(0.1)

In [139]:
xc, yc = maxX//2, maxY//2
rx = 10
ry = 10
for ix in range(maxX):
    for iy in range(maxY):
        distance_ratio = abs(ix - xc)/rx + abs(iy - yc)/ry
        if distance_ratio <= 1:
            A4[ix,iy] = 1

In [141]:
succesful_particles = 0
total_steps = 0
max_steps_per_particle = maxX*maxY*2
nFrames=50
record_step = 10
frame_index = 0

for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x = maxX - 1
    y = maxY//2; #always start at upper limit
    current_steps = 0
    attached = False

    while not attached and current_steps < max_steps_per_particle:
        current_steps += 1
        x_org,y_org = x,y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.1):
            x += 1
        elif(r < 0.6):
            x -= 1
        elif(r < 0.8):
            y += 1
        else:
            y -= 1
        #boundaries
        if x >= maxX:
            x = x_org
            continue
        if x<0:
            succesful_particles += 1
            total_steps += current_steps
            break
        
        if y<=1 or y>= 38: 
            total_steps += current_steps
            break
        if A4[x,y] == 1:
            total_steps += current_steps
            break

        if current_steps % record_step == 0 and frame_index < nFrames:
            B[frame_index,x,y] += 1
            frame_index +=1
probability = succesful_particles/nParticles
print("The number of particles that made it to the end is", succesful_particles)
print("The probability that a particle reaches the end of the pip is", probability*100, "percent")

for f in range(nFrames):
    display(A4,B[f,:,:])

The number of particles that made it to the end is 1011
The probability that a particle reaches the end of the pip is 5.055 percent


In [142]:
#The percent of particles that make it through goes back down a lot closer to the percent of the original shape, but it is slightly higher at around 5%.

In [143]:
#The half as tall Rhombus creates a lot more space for particles to get through than the original and half as wide rhombuses. This is why the percent of particles that make it through is much higher

In [ ]:
#