In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A):
    maxX = A.shape[0]
    maxY = A.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [3]:
nParticles = 10000
maxX = 320
maxY = 320

In [4]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A[:,0] = 1
print(A.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
#test the display routine
display(A)

In [2]:
# To save computer time, we want to inject the new particle not too far
# above growing aggregate. We inject at on a line 'yStart', which
# keeps being increased so that it is always 'yBuffer' lines above the
# highest structure
yBuffer = 5
yStart  = 1 + yBuffer

In [2]:
for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x  = np.random.randint(0,maxX)
    y  = yStart; #always start at upper limit

    while True:
        xOrg = x
        yOrg = y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.25):
            x += 1
        elif(r < 0.5):
            x -= 1
        elif(r < 0.75):
            y += 1
        else:
            y -= 1
        #now apply periodic boundary conditions to 'x'
        ...
        if(x < 0):
            x = maxX - 1
        elif(x >= maxX):
            x = 0
        
        if (A[x,y] == 1 or y>yStart): 
            x = xOrg
            y = yOrg
            continue; # if this site has been taken try moving in a different direction
        
        #determine the x coordionates of the left and right neighbors
        #store them in 'xm' and 'xp' and apply periodic boundary conditions again
        xp = (x + 1) % maxX
        xm = (x - 1 + maxX) % maxX
        yp = y + 1
        ym = y - 1
 
        # Determine if any neighboring site is occupied
        # if that is the case, enter the following 'if' clause
        if (A[xp,y] == 1 or A[xm,y] == 1 or A[x,yp] == 1 or A[x,ym] == 1): 
            A[x,y] = 1
            if (y+yBuffer>yStart and y+yBuffer<maxY): 
                yStart = y+yBuffer

            if (i%1000==0): 
                print(f'i= {i} \tx={x} \ty={y} \tyStart={yStart}')

            nNewParticlesPerFrame = 1000 
            if (i%nNewParticlesPerFrame==0): 
                display(A)
                
            break # particle was attached, break out of current loop and insert next one
            
    if (yStart+1==maxY): 
        print(f'Structures reached Y limit after only {i} particles')
        break

display(A)

NameError: name 'nParticles' is not defined

In [11]:
#Periodic boundaries are not needed because y is already bounded by y=0 and y=yStart

In [18]:
#For question 6 I set boundaries for maxX and maxY to 320 for both, this resulted in the animation runing for longer.

In [3]:
nParticles_2 = 10000
maxX_2 = 200
maxY_2 = 600
def display(A_2):
    maxX_2 = A_2.shape[0]
    maxY_2 = A_2.shape[1]
    B_2 = np.zeros((maxY_2, maxX_2))
    for ix_2 in range(0,maxX_2):
        for iy_2 in range(0,maxY_2):
            B_2[maxY_2-1-iy_2,ix_2] = A_2[ix_2,iy_2]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX_2*maxY_2]
    plt.imshow(B_2); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)
A_2 = np.zeros((maxX_2, maxY_2))
A_2[:,0] = 1

In [4]:
for i in range(0,nParticles_2):
    # Compute new starting point on the line y=yStart
    x_2  = np.random.randint(0,maxX_2)
    y_2  = yStart; #always start at upper limit

    while True:
        xOrg = x_2
        yOrg = y_2

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.25):
            x_2 += 1
        elif(r < 0.5):
            x_2 -= 1
        elif(r < 0.75):
            y_2 += 1
        else:
            y_2 -= 1
        #now apply periodic boundary conditions to 'x'
        ...
        if(x_2 < 0):
            x_2 = maxX_2 - 1
        elif(x_2 >= maxX_2):
            x_2 = 0
        
        if (A_2[x_2,y_2] == 1 or y_2>yStart): 
            x_2 = xOrg
            y_2 = yOrg
            continue; # if this site has been taken try moving in a different direction
        
        #determine the x coordionates of the left and right neighbors
        #store them in 'xm' and 'xp' and apply periodic boundary conditions again
        xp_2 = (x_2 + 1) % maxX_2
        xm_2 = (x_2 - 1 + maxX_2) % maxX_2
        yp_2 = y_2 + 1
        ym_2 = y_2 - 1
 
        # Determine if any neighboring site is occupied
        # if that is the case, enter the following 'if' clause
        if (A_2[xp_2,y_2] == 1 or A_2[xm_2,y_2] == 1 or A_2[x_2,yp_2] == 1 or A_2[x_2,ym_2] == 1): 
            A_2[x_2,y_2] = 1
            if (y_2+yBuffer>yStart and y_2+yBuffer<maxY_2): 
                yStart = y_2+yBuffer

            if (i%1000==0): 
                print(f'i= {i} \tx={x_2} \ty={y_2} \tyStart={yStart}')

            nNewParticlesPerFrame = 1000 
            if (i%nNewParticlesPerFrame==0): 
                display(A_2)
                
            break # particle was attached, break out of current loop and insert next one
            
    if (yStart+1==maxY_2): 
        print(f'Structures reached Y limit after only {i} particles')
        break

display(A_2)

i= 0 	x=48 	y=1 	yStart=6
i= 1000 	x=112 	y=28 	yStart=40
i= 2000 	x=98 	y=60 	yStart=78
i= 3000 	x=123 	y=94 	yStart=114
i= 4000 	x=44 	y=106 	yStart=152
i= 5000 	x=41 	y=184 	yStart=189
i= 6000 	x=186 	y=214 	yStart=227
i= 7000 	x=192 	y=255 	yStart=273
i= 8000 	x=43 	y=296 	yStart=308
i= 9000 	x=166 	y=329 	yStart=343


In [5]:
#For part 7 I have tried to set a much higher max Y value than max X value to try and get a long singular tree by the end of the simulation.
#This has been kind of successful but not completely and I am not sure what I should change.

In [6]:
#Part 2 (For each simulation I reset the kernel and only run the relevant cells)

In [3]:
nParticles_3 = 10000
maxX_3 = 320
maxY_3 = 320
def display(A_3):
    maxX_3 = A_3.shape[0]
    maxY_3 = A_3.shape[1]
    B_3 = np.zeros((maxY_3, maxX_3))
    for ix_3 in range(0,maxX_3):
        for iy_3 in range(0,maxY_3):
            B_3[maxY_3-1-iy_3,ix_3] = A_3[ix_3,iy_3]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX_3*maxY_3]
    plt.imshow(B_3); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)
A_3 = np.zeros((maxX_3, maxY_3))
A_3[:,0] = 1

In [4]:
for i in range(0,nParticles_3):
    # Compute new starting point on the line y=yStart
    x_3  = np.random.randint(0,maxX_3)
    y_3  = yStart; #always start at upper limit

    while True:
        xOrg = x_3
        yOrg = y_3

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.4):
            x_3 += 1
        elif(r < 0.5):
            x_3 -= 1
        elif(r < 0.75):
            y_3 += 1
        else:
            y_3 -= 1
        #now apply periodic boundary conditions to 'x'
        ...
        if(x_3 < 0):
            x_3 = maxX_3 - 1
        elif(x_3 >= maxX_3):
            x_3 = 0
        
        if (A_3[x_3,y_3] == 1 or y_3>yStart): 
            x_3 = xOrg
            y_3 = yOrg
            continue; # if this site has been taken try moving in a different direction
        
        #determine the x coordionates of the left and right neighbors
        #store them in 'xm' and 'xp' and apply periodic boundary conditions again
        xp_3 = (x_3 + 1) % maxX_3
        xm_3 = (x_3 - 1 + maxX_3) % maxX_3
        yp_3 = y_3 + 1
        ym_3 = y_3 - 1
 
        # Determine if any neighboring site is occupied
        # if that is the case, enter the following 'if' clause
        if (A_3[xp_3,y_3] == 1 or A_3[xm_3,y_3] == 1 or A_3[x_3,yp_3] == 1 or A_3[x_3,ym_3] == 1): 
            A_3[x_3,y_3] = 1
            if (y_3+yBuffer>yStart and y_3+yBuffer<maxY_3): 
                yStart = y_3+yBuffer

            if (i%1000==0): 
                print(f'i= {i} \tx={x_3} \ty={y_3} \tyStart={yStart}')

            nNewParticlesPerFrame = 1000 
            if (i%nNewParticlesPerFrame==0): 
                display(A_3)
                
            break # particle was attached, break out of current loop and insert next one
            
    if (yStart+1==maxY_3): 
        print(f'Structures reached Y limit after only {i} particles')
        break

display(A_3)

i= 0 	x=64 	y=1 	yStart=6
i= 1000 	x=151 	y=52 	yStart=68
i= 2000 	x=34 	y=140 	yStart=147
i= 3000 	x=258 	y=224 	yStart=229
i= 4000 	x=183 	y=300 	yStart=305
Structures reached Y limit after only 4182 particles


In [5]:
#The dendrites are moving mainly against the flow of the pipe
#The particles that move to the right stick, but those that move to the left penetrate "screen" which is the flow bias.
#This creates the appearance of movement towards the left.

In [7]:
#Part 3
#I reset the probabilities of the particles moving right and left to each 25%

In [3]:
nParticles_4 = 10000
maxX_4 = 320
maxY_4 = 320
#I am adding a p value, which I will change during trials
p = 0.5
def display(A_4):
    maxX_4 = A_4.shape[0]
    maxY_4 = A_4.shape[1]
    B_4 = np.zeros((maxY_4, maxX_4))
    for ix_4 in range(0,maxX_4):
        for iy_4 in range(0,maxY_4):
            B_4[maxY_4-1-iy_4,ix_4] = A_4[ix_4,iy_4]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib tk 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX_4*maxY_4]
    plt.imshow(B_4); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)
A_4 = np.zeros((maxX_4, maxY_4))
A_4[:,0] = 1

In [4]:
for i in range(0,nParticles_4):
    # Compute new starting point on the line y=yStart
    x_4  = np.random.randint(0,maxX_4)
    y_4  = yStart; #always start at upper limit

    while True:
        xOrg = x_4
        yOrg = y_4

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly
        ...
        if(r < 0.25):
            x_4 += 1
        elif(r < 0.5):
            x_4 -= 1
        elif(r < 0.75):
            y_4 += 1
        else:
            y_4 -= 1
        #now apply periodic boundary conditions to 'x'
        ...
        if(x_4 < 0):
            x_4 = maxX_4 - 1
        elif(x_4 >= maxX_4):
            x_4 = 0
        
        if (A_4[x_4,y_4] == 1 or y_4>yStart): 
            x_3 = xOrg
            y_4 = yOrg
            continue; # if this site has been taken try moving in a different direction
        
        #determine the x coordionates of the left and right neighbors
        #store them in 'xm' and 'xp' and apply periodic boundary conditions again
        xp_4 = (x_4 + 1) % maxX_4
        xm_4 = (x_4 - 1 + maxX_4) % maxX_4
        yp_4 = y_4 + 1
        ym_4 = y_4 - 1
 
        # Determine if any neighboring site is occupied
        # if that is the case, enter the following 'if' clause
        if (A_4[xp_4,y_4] == 1 or A_4[xm_4,y_4] == 1 or A_4[x_4,yp_4] == 1 or A_4[x_4,ym_4] == 1): 
            r_stick = np.random.random()
            if (r_stick < p):
                A_4[x_4,y_4] = 1 #This if loop checks if the particle sticks or not
            if (y_4+yBuffer>yStart and y_4+yBuffer<maxY_4): 
                yStart = y_4+yBuffer

            if (i%1000==0): 
                print(f'i= {i} \tx={x_4} \ty={y_4} \tyStart={yStart}')

            nNewParticlesPerFrame = 1000 
            if (i%nNewParticlesPerFrame==0): 
                display(A_4)
                
            break # particle was attached, break out of current loop and insert next one
            
    if (yStart+1==maxY_4): 
        print(f'Structures reached Y limit after only {i} particles')
        break

display(A_4)

i= 0 	x=174 	y=1 	yStart=6
i= 1000 	x=39 	y=6 	yStart=17
i= 2000 	x=52 	y=20 	yStart=31
i= 3000 	x=24 	y=18 	yStart=42
i= 4000 	x=264 	y=35 	yStart=63
i= 5000 	x=208 	y=52 	yStart=75
i= 6000 	x=194 	y=68 	yStart=86
i= 7000 	x=69 	y=76 	yStart=99
i= 8000 	x=86 	y=92 	yStart=109
i= 9000 	x=143 	y=113 	yStart=120


In [ ]:
#The structures are very compact when p = 0.1
#The structures are much less compact when p = 0.9, they look very similar to those in part 1
#When p = 0.5, the structures are a level of compact that is in-between p = 0.1 and p = 0.9, which makes sense.